version: "3"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: happyuser
      POSTGRES_PASSWORD: happypass
      POSTGRES_DB: happydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: